#!/usr/bin/env bash
# Regenerate requirements.txt — the file Vercel actually installs.
#
# `uv export` resolves the *runtime* dependency set only (no dev, no pipeline
# group, no editable install of this package), which is exactly what keeps the
# serverless bundle under Vercel's 500 MB limit.
set -euo pipefail
cd "$(dirname "$0")/.."

uv export \
  --no-dev \
  --no-emit-project \
  --no-hashes \
  --format requirements.txt \
  --output-file requirements.txt

echo "# Generated by scripts/gen_requirements.sh -- do not edit by hand." | \
  cat - requirements.txt > requirements.txt.tmp && mv requirements.txt.tmp requirements.txt

echo "wrote requirements.txt ($(grep -c '==' requirements.txt) pinned packages)"
